using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.Data.OleDb;
using System.Collections;
using DevExpress.XtraPrinting;

namespace SDI_LCS
{
    public partial class Form_Traffic_Basic : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        Form1 Main;
        DataTable Grid_Table;
        public ArrayList Traffic_Node;

        public Form_Traffic_Basic()
        {
            Traffic_Node = new ArrayList();
            Grid_Table = new DataTable();

            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
        }
        public Form_Traffic_Basic(Form1 CS_Main)
        {
            Main = CS_Main;
            InitializeComponent();

            Traffic_Node = new ArrayList();
            Grid_Table = new DataTable();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {


            Insert_Excel_Data();
            Select_Traffic_Basic();
        }
        public void MappingGrid()
        {
            for (int i = 0; i < Grid_Table.Rows.Count; i++)
            {
                Main.m_stTraffic[i].idx_Current_Use = Convert.ToString(Grid_Table.Rows[i][0]);
                Main.m_stTraffic[i].idx_Start_Current = Convert.ToString(Grid_Table.Rows[i][1]);
                Main.m_stTraffic[i].idx_End_Current = Convert.ToString(Grid_Table.Rows[i][2]);

                Main.m_stTraffic[i].idx_Goal_Use = Convert.ToString(Grid_Table.Rows[i][3]);
                Main.m_stTraffic[i].idx_Start_Goal = Convert.ToString(Grid_Table.Rows[i][4]);
                Main.m_stTraffic[i].idx_End_Goal = Convert.ToString(Grid_Table.Rows[i][5]);



                Main.m_stTraffic[i].i_Current_Use = Convert.ToString(Grid_Table.Rows[i][12]);
                Main.m_stTraffic[i].i_Start_Current = Convert.ToString(Grid_Table.Rows[i][13]);
                Main.m_stTraffic[i].i_End_Current = Convert.ToString(Grid_Table.Rows[i][14]);

                Main.m_stTraffic[i].i_Goal_Use = Convert.ToString(Grid_Table.Rows[i][15]);
                Main.m_stTraffic[i].i_Start_Goal = Convert.ToString(Grid_Table.Rows[i][16]);
                Main.m_stTraffic[i].i_End_Goal = Convert.ToString(Grid_Table.Rows[i][17]);


                Traffic_Node.Add(Main.m_stTraffic[i]);
            }
        }

        public void Insert_Excel_Data()
        {
            string idx_Start_Current;
            string idx_End_Current;
            string idx_Start_Goal;
            string idx_End_Goal;

            string i_Start_Current;
            string i_End_Current;
            string i_Start_Goal;
            string i_End_Goal;


            idx_Start_Current = TB_idx_S_Current.Text;
            idx_End_Current = TB_idx_E_Current.Text;
            idx_Start_Goal = TB_idx_S_Goal.Text;
            idx_End_Goal = TB_idx_E_Goal.Text;


            i_Start_Current = TB_i_S_Current.Text;
            i_End_Current = TB_i_E_Current.Text;
            i_Start_Goal = TB_i_S_Goal.Text;
            i_End_Goal = TB_i_E_Goal.Text;


//            string test;
            OleDbCommand dbCommand;
            string conStr = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source= C:\\SDI_DATA\\Traffic_Basic.xlsx;Extended Properties=""Excel 12.0;HDR=YES;""";
            OleDbConnection excelConnection = new OleDbConnection(conStr);
            excelConnection.Open();


            dbCommand = new OleDbCommand("INSERT INTO [Sheet$](사용여부_C_I,시작위치_I,종료위치_I,사용여부_G_I,시작목적지_I,종료목적지_I,사용여부_C_U,시작위치_U,종료위치_U,사용여부_G_U,시작목적지_U,종료목적지_U) VALUES ("
              + "'사용'," + idx_Start_Current + "," + idx_End_Current + "," + "'미사용'," + idx_Start_Goal + "," + idx_End_Goal + "," + "'사용'," + i_Start_Current + "," + i_End_Current + "," + "'미사용'," + i_Start_Goal + "," + i_End_Goal + ")", excelConnection);
            dbCommand.ExecuteNonQuery();

            excelConnection.Close();
        }
        public void Select_Traffic_Basic()
        {
            //            string test;

            string conStr = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source= C:\\SDI_DATA\\Traffic_Basic.xlsx;Extended Properties=""Excel 12.0;HDR=YES;""";
            OleDbConnection excelConnection = new OleDbConnection(conStr);
            excelConnection.Open();

            Grid_Table = new DataTable();
            string strSQL = "SELECT * FROM [Sheet$] ORDER BY 시작위치_I";
            OleDbCommand dbCommand = new OleDbCommand(strSQL, excelConnection);
            OleDbDataAdapter dataAdapter = new OleDbDataAdapter(dbCommand);



            dataAdapter.Fill(Grid_Table);
            Grid_Traffic_Setting.DataSource = Grid_Table;
            Traffic_Node.Clear();
            for (int i = 0; i < Grid_Table.Rows.Count; i++)
            {
                Main.m_stTraffic[i].idx_Current_Use = Convert.ToString(Grid_Table.Rows[i][0]);
                Main.m_stTraffic[i].idx_Start_Current = Convert.ToString(Grid_Table.Rows[i][1]);
                Main.m_stTraffic[i].idx_End_Current = Convert.ToString(Grid_Table.Rows[i][2]);

                Main.m_stTraffic[i].idx_Goal_Use = Convert.ToString(Grid_Table.Rows[i][3]);
                Main.m_stTraffic[i].idx_Start_Goal = Convert.ToString(Grid_Table.Rows[i][4]);
                Main.m_stTraffic[i].idx_End_Goal = Convert.ToString(Grid_Table.Rows[i][5]);

                Main.m_stTraffic[i].i_Current_Use = Convert.ToString(Grid_Table.Rows[i][6]);
                Main.m_stTraffic[i].i_Start_Current = Convert.ToString(Grid_Table.Rows[i][7]);
                Main.m_stTraffic[i].i_End_Current = Convert.ToString(Grid_Table.Rows[i][8]);

                Main.m_stTraffic[i].i_Goal_Use = Convert.ToString(Grid_Table.Rows[i][9]);
                Main.m_stTraffic[i].i_Start_Goal = Convert.ToString(Grid_Table.Rows[i][10]);
                Main.m_stTraffic[i].i_End_Goal = Convert.ToString(Grid_Table.Rows[i][11]);

                Traffic_Node.Add(Main.m_stTraffic[i]);
            }


            // dispose used objects
            Grid_Table.Dispose();
            dataAdapter.Dispose();
            dbCommand.Dispose();

            excelConnection.Close();
            excelConnection.Dispose();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            string str_tmpFilterString;

            str_tmpFilterString = gridView1.ActiveFilterString;
            gridView1.ActiveFilterString = "";

            XlsxExportOptionsEx xlsxOptions = new XlsxExportOptionsEx();
            xlsxOptions.ShowGridLines = true;   // 라인출력 
            Grid_Traffic_Setting.ExportToXlsx("C:\\SDI_DATA\\Traffic_Basic.xlsx", xlsxOptions);
            Select_Traffic_Basic();

            gridView1.ActiveFilterString = str_tmpFilterString;
        }

        private void Form_Traffic_Basic_Shown(object sender, EventArgs e)
        { 
            Select_Traffic_Basic();
        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            int i = 0;

            if (gridView1 == null || gridView1.SelectedRowsCount == 0) return;
            DataRow[] rows = new DataRow[gridView1.SelectedRowsCount];

            for (i = 0; i < gridView1.SelectedRowsCount; i++)
            {
                rows[i] = gridView1.GetDataRow(gridView1.GetSelectedRows()[i]);
            }

            gridView1.BeginSort();

            try
            {
                foreach (DataRow row in rows)
                    row.Delete();
            }
            finally
            {
                gridView1.EndSort();
            }
            Grid_Traffic_Setting.ExportToXlsx("C:\\SDI_DATA\\Traffic_Basic.xlsx");
            Select_Traffic_Basic();
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}