using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using System.Data.OleDb;
using System.Collections;

namespace SDI_LCS
{
    public partial class Form_Traffic_Cell : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        Form1 Main;
        DataTable Grid_Table;
        public ArrayList Traffic_Cell;
        public Form_Traffic_Cell()
        {
            InitializeComponent();
            Grid_Table = new DataTable();
            Traffic_Cell = new ArrayList();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a ExcelDataSource
            excelDataSource1.Fill();
        }
        public Form_Traffic_Cell(Form1 CS_Main)
        {
            Main = CS_Main;
            InitializeComponent();
            Grid_Table = new DataTable();
            Traffic_Cell = new ArrayList();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Insert_Excel_Data();
            Select_Traffic_Cell();
        }
        public void Insert_Excel_Data()
        {
            int Start_Node;
            int End_Node;
            string Way;
            int Cell_Count;

            Start_Node = Convert.ToInt32(TB_Start_Index.Text);
            End_Node = Convert.ToInt32(TB_End_Index.Text);
            Way = CB_Way.Text;
            Cell_Count = Convert.ToInt32(TB_Cell_Count.Text);

//            string test;
            OleDbCommand dbCommand;
            string conStr = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source= C:\\SDI_DATA\\Traffic_Cell.xlsx;Extended Properties=""Excel 12.0;HDR=YES;""";
            OleDbConnection excelConnection = new OleDbConnection(conStr);
            excelConnection.Open();

            dbCommand = new OleDbCommand("INSERT INTO [Sheet$](시작_구간,종료_구간,방향,칸수) VALUES (" + Start_Node + "," + End_Node + ",'" + Way + "'," + Cell_Count + ")", excelConnection);
            dbCommand.ExecuteNonQuery();
            excelConnection.Close();
        }
        public void Select_Traffic_Cell()
        {
            string conStr = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source= C:\\SDI_DATA\\Traffic_Cell.xlsx;Extended Properties=""Excel 12.0;HDR=YES;""";
            OleDbConnection excelConnection = new OleDbConnection(conStr);
            excelConnection.Open();

            Grid_Table = new DataTable();
            string strSQL = "SELECT * FROM [Sheet$]";
            OleDbCommand dbCommand = new OleDbCommand(strSQL, excelConnection);
            OleDbDataAdapter dataAdapter = new OleDbDataAdapter(dbCommand);

            dataAdapter.Fill(Grid_Table);
            Grid_Traffic_Cell.DataSource = Grid_Table;
            Traffic_Cell.Clear();
            for (int i = 0; i < Grid_Table.Rows.Count; i++)
            {
                Main.m_stTraffic_Cell[i].Start_Index = Convert.ToInt32(Grid_Table.Rows[i][0]);
                Main.m_stTraffic_Cell[i].End_Index = Convert.ToInt32(Grid_Table.Rows[i][1]);
                Main.m_stTraffic_Cell[i].Way = Convert.ToString(Grid_Table.Rows[i][2]);
                Main.m_stTraffic_Cell[i].Cell_Count = Convert.ToInt32(Grid_Table.Rows[i][3]);

                Traffic_Cell.Add(Main.m_stTraffic_Cell[i]);
            }
            // dispose used objects
            Grid_Table.Dispose();
            dataAdapter.Dispose();
            dbCommand.Dispose();

            excelConnection.Close();
            excelConnection.Dispose();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            string str_tmpFilterString;

            str_tmpFilterString = gridView1.ActiveFilterString;
            gridView1.ActiveFilterString = "";

            Grid_Traffic_Cell.ExportToXlsx("C:\\SDI_DATA\\Traffic_Cell.xlsx");
            Select_Traffic_Cell();



            gridView1.ActiveFilterString = str_tmpFilterString;
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            int i = 0;

            if (gridView1 == null || gridView1.SelectedRowsCount == 0) return;
            DataRow[] rows = new DataRow[gridView1.SelectedRowsCount];

            for (i = 0; i < gridView1.SelectedRowsCount; i++)
            {
                rows[i] = gridView1.GetDataRow(gridView1.GetSelectedRows()[i]);
            }

            gridView1.BeginSort();

            try
            {
                foreach (DataRow row in rows)
                    row.Delete();
            }
            finally
            {
                gridView1.EndSort();
            }
            Grid_Traffic_Cell.ExportToXlsx("C:\\SDI_DATA\\Traffic_Cell.xlsx");
            Select_Traffic_Cell();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void Form_Traffic_Cell_Shown(object sender, EventArgs e)
        {
            Select_Traffic_Cell();
        }
    }
}